# Generated by Django 4.0.2 on 2022-02-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='passcode',
            field=models.CharField(max_length=100),
        ),
    ]
